name: Build APK

on:
  push:
    tags: ['v*']

jobs:
  build-apk:
    name: Build APK with Buildozer
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Accept SDK licenses
        run: |
          yes | sdkmanager --licenses
        # Опционально: добавьте проверку, что лицензии приняты
        # echo "SDK licenses accepted"

      - name: Build APK using Kivy Buildozer Docker
        run: |
          docker run --rm -v $(pwd):/home/user/hostcwd kivy/buildozer android debug

      - name: Upload APK to Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.repository.releases[0].upload_url }}
          asset_path: ./bin/rttygen-0.1-debug.apk
          asset_name: rtty_generator.apk
          asset_content_type: application/vnd.android.package-archive
