name: Flutter Build

on:
  push:
    branches:
      - main  # Запускает сборку при пуше в ветку main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest  # Используем Ubuntu для сборки (подходит для APK)

    steps:
      - name: Check out code
        uses: actions/checkout@v3  # Клонируем репозиторий

      - name: Set up Flutter
        uses: subosito/flutter-action@v3
        with:
          flutter-version: '3.0.0'  # Укажите нужную версию Flutter

      - name: Install dependencies
        run: flutter pub get  # Загружаем зависимости

      - name: Build APK
        run: flutter build apk --release  # Собираем релизный APK

      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: apk
          path: build/app/outputs/flutter-apk/app-release.apk  # Путь к собранному APK
