name: Build APK with Buildozer
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install Buildozer
        run: |
          pip3 install  --upgrade buildozer
          sudo apt update
          sudo apt install -y git zip unzip 
          sudo apt install -y openjdk-17-jdk python3-pip 
          sudo apt install -y autoconf libtool pkg-config zlib1g-dev libncurses5-dev libncursesw5-dev libtinfo6 cmake libffi-dev libssl-dev
          pip3 install --upgrade Cython==0.29.33 virtualenv
      - name: Clean Android SDK cache
        run: |
          rm -rf ~/.android/repositories.cfg
          rm -rf ~/.android/cache
          rm -rf ~/.android/avd
      - name: Install SDK
        uses: android-actions/setup-android@v4
        with:
          cmdline-tools-version: 'latest'
          accept-android-sdk-licenses: true
          log-accepted-android-sdk-licenses: true
          packages: |
            platform-tools
            platforms;android-33
            build-tools;33.0.0
            cmake;3.22.1
            ndk;25.1.8937393
      - name: Set Android environment variables
        run: |
          echo "ANDROID_SDK_ROOT=${{ env.ANDROID_SDK_ROOT }}" >> $GITHUB_ENV
          echo "ANDROID_HOME=${{ env.ANDROID_SDK_ROOT }}" >> $GITHUB_ENV
          echo "PATH=${{ env.ANDROID_SDK_ROOT }}/cmdline-tools/latest/bin:${{ env.PATH }}" >> $GITHUB_ENV
      - name: Build APK
        run: 
          buildozer -v android clean
          buildozer -v android debug
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-apk
          path: bin/*.apk
